/* Generated By:JavaCC: Do not edit this line. PathExpressionConstants.java */
package dcc.agent.server.service.swget.regExpression.parser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface PathExpressionConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int PLUS = 5;
	/** RegularExpression Id. */
	int KLEENE = 6;
	/** RegularExpression Id. */
	int QUESTION = 7;
	/** RegularExpression Id. */
	int INTERVAL = 8;
	/** RegularExpression Id. */
	int LBRACKET = 9;
	/** RegularExpression Id. */
	int RBRACKET = 10;
	/** RegularExpression Id. */
	int LANGLEBRACKET = 11;
	/** RegularExpression Id. */
	int RANGLEBRACKET = 12;
	/** RegularExpression Id. */
	int OR = 13;
	/** RegularExpression Id. */
	int AND = 14;
	/** RegularExpression Id. */
	int PREDICATE = 15;
	/** RegularExpression Id. */
	int NUMBER = 16;
	/** RegularExpression Id. */
	int SPRQLQUERY = 17;
	/** RegularExpression Id. */
	int ACTION = 18;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\n\"", "\"\\r\"",
			"\"\\r\\n\"", "\"+\"", "\"*\"", "\"?\"", "\"-\"", "\"(\"", "\")\"",
			"\"<\"", "\">\"", "\"|\"", "\"/\"", "<PREDICATE>", "<NUMBER>",
			"<SPRQLQUERY>", "<ACTION>", };

}
