/* Generated By:JavaCC: Do not edit this line. PathExpressionTokenManager.java */
package dcc.agent.server.service.swget.regExpression.parser;

/** Token Manager. */
public class PathExpressionTokenManager implements PathExpressionConstants {

	/** Debug output. */
	public java.io.PrintStream debugStream = System.out;
	static final long[] jjbitVec0 = { 0x0L, 0x0L, 0xffffffffffffffffL,
			0xffffffffffffffffL };
	static final int[] jjnextStates = { 1, 4, 2, 3, 8, 9, 11, 12, };
	/** Token literal values. */
	public static final String[] jjstrLiteralImages = { "", null, null, null,
			null, "\53", "\52", "\77", "\55", "\50", "\51", "\74", "\76",
			"\174", "\57", null, null, null, null, };
	/** Lexer state names. */
	public static final String[] lexStateNames = { "DEFAULT", };
	static final long[] jjtoToken = { 0x7ffe1L, };
	static final long[] jjtoSkip = { 0x1eL, };
	protected SimpleCharStream input_stream;
	private final int[] jjrounds = new int[16];
	private final int[] jjstateSet = new int[32];
	protected char curChar;

	int curLexState = 0;

	int defaultLexState = 0;
	int jjnewStateCnt;
	int jjround;
	int jjmatchedPos;
	int jjmatchedKind;

	/** Constructor. */
	public PathExpressionTokenManager(SimpleCharStream stream) {
		if (SimpleCharStream.staticFlag)
			throw new Error(
					"ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
		input_stream = stream;
	}

	/** Constructor. */
	public PathExpressionTokenManager(SimpleCharStream stream, int lexState) {
		this(stream);
		SwitchTo(lexState);
	}

	/** Get the next Token. */
	public Token getNextToken() {
		Token matchedToken;
		int curPos = 0;

		EOFLoop: for (;;) {
			try {

				curChar = input_stream.BeginToken();
			} catch (java.io.IOException e) {
				jjmatchedKind = 0;
				matchedToken = jjFillToken();
				return matchedToken;
			}

			try {
				input_stream.backup(0);
				while (curChar <= 32 && (0x100000400L & (1L << curChar)) != 0L)
					curChar = input_stream.BeginToken();
			} catch (java.io.IOException e1) {
				continue EOFLoop;
			}
			jjmatchedKind = 0x7fffffff;
			jjmatchedPos = 0;
			curPos = jjMoveStringLiteralDfa0_0();
			if (jjmatchedKind != 0x7fffffff) {
				if (jjmatchedPos + 1 < curPos)
					input_stream.backup(curPos - jjmatchedPos - 1);
				if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
					matchedToken = jjFillToken();
					return matchedToken;
				} else {
					continue EOFLoop;
				}
			}
			int error_line = input_stream.getEndLine();
			int error_column = input_stream.getEndColumn();
			String error_after = null;
			boolean EOFSeen = false;
			try {
				input_stream.readChar();
				input_stream.backup(1);
			} catch (java.io.IOException e1) {
				EOFSeen = true;
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
				if (curChar == '\n' || curChar == '\r') {
					error_line++;
					error_column = 0;
				} else
					error_column++;
			}
			if (!EOFSeen) {
				input_stream.backup(1);
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
			}
			throw new TokenMgrError(EOFSeen, curLexState, error_line,
					error_column, error_after, curChar,
					TokenMgrError.LEXICAL_ERROR);
		}
	}

	private void jjAddStates(int start, int end) {
		do {
			jjstateSet[jjnewStateCnt++] = jjnextStates[start];
		} while (start++ != end);
	}

	private void jjCheckNAdd(int state) {
		if (jjrounds[state] != jjround) {
			jjstateSet[jjnewStateCnt++] = state;
			jjrounds[state] = jjround;
		}
	}

	private void jjCheckNAddTwoStates(int state1, int state2) {
		jjCheckNAdd(state1);
		jjCheckNAdd(state2);
	}

	protected Token jjFillToken() {
		final Token t;
		final String curTokenImage;
		final int beginLine;
		final int endLine;
		final int beginColumn;
		final int endColumn;
		String im = jjstrLiteralImages[jjmatchedKind];
		curTokenImage = (im == null) ? input_stream.GetImage() : im;
		beginLine = input_stream.getBeginLine();
		beginColumn = input_stream.getBeginColumn();
		endLine = input_stream.getEndLine();
		endColumn = input_stream.getEndColumn();
		t = Token.newToken(jjmatchedKind, curTokenImage);

		t.beginLine = beginLine;
		t.endLine = endLine;
		t.beginColumn = beginColumn;
		t.endColumn = endColumn;

		return t;
	}

	private int jjMoveNfa_0(int startState, int curPos) {
		int startsAt = 0;
		jjnewStateCnt = 16;
		int i = 1;
		jjstateSet[0] = startState;
		int kind = 0x7fffffff;
		for (;;) {
			if (++jjround == 0x7fffffff)
				ReInitRounds();
			if (curChar < 64) {
				long l = 1L << curChar;
				do {
					switch (jjstateSet[--i]) {
					case 0:
						if ((0x3fe000000000000L & l) != 0L) {
							if (kind > 16)
								kind = 16;
							jjCheckNAdd(6);
						} else if (curChar == 60)
							jjAddStates(0, 1);
						break;
					case 2:
						if ((0x7ffe80800000000L & l) != 0L)
							jjAddStates(2, 3);
						break;
					case 3:
						if (curChar == 62 && kind > 15)
							kind = 15;
						break;
					case 5:
						if ((0x3fe000000000000L & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjCheckNAdd(6);
						break;
					case 6:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjCheckNAdd(6);
						break;
					case 8:
						jjAddStates(4, 5);
						break;
					case 11:
						jjAddStates(6, 7);
						break;
					default:
						break;
					}
				} while (i != startsAt);
			} else if (curChar < 128) {
				long l = 1L << (curChar & 077);
				do {
					switch (jjstateSet[--i]) {
					case 0:
						if (curChar == 65)
							jjstateSet[jjnewStateCnt++] = 14;
						else if (curChar == 91)
							jjCheckNAdd(8);
						break;
					case 1:
						if ((0x7fffffe07fffffeL & l) != 0L)
							jjCheckNAddTwoStates(2, 3);
						else if (curChar == 95)
							jjCheckNAdd(3);
						break;
					case 2:
						if ((0x7fffffe07fffffeL & l) != 0L)
							jjCheckNAddTwoStates(2, 3);
						break;
					case 4:
						if (curChar == 95)
							jjCheckNAdd(3);
						break;
					case 7:
						if (curChar == 91)
							jjCheckNAdd(8);
						break;
					case 8:
						if ((0xffffffffdfffffffL & l) != 0L)
							jjCheckNAddTwoStates(8, 9);
						break;
					case 9:
						if (curChar == 93 && kind > 17)
							kind = 17;
						break;
					case 10:
						if (curChar == 91)
							jjCheckNAdd(11);
						break;
					case 11:
						if ((0xffffffffdfffffffL & l) != 0L)
							jjCheckNAddTwoStates(11, 12);
						break;
					case 12:
						if (curChar == 93 && kind > 18)
							kind = 18;
						break;
					case 13:
						if (curChar == 84)
							jjstateSet[jjnewStateCnt++] = 10;
						break;
					case 14:
						if (curChar == 67)
							jjstateSet[jjnewStateCnt++] = 13;
						break;
					case 15:
						if (curChar == 65)
							jjstateSet[jjnewStateCnt++] = 14;
						break;
					default:
						break;
					}
				} while (i != startsAt);
			} else {
				int i2 = (curChar & 0xff) >> 6;
				long l2 = 1L << (curChar & 077);
				do {
					switch (jjstateSet[--i]) {
					case 8:
						if ((jjbitVec0[i2] & l2) != 0L)
							jjAddStates(4, 5);
						break;
					case 11:
						if ((jjbitVec0[i2] & l2) != 0L)
							jjAddStates(6, 7);
						break;
					default:
						break;
					}
				} while (i != startsAt);
			}
			if (kind != 0x7fffffff) {
				jjmatchedKind = kind;
				jjmatchedPos = curPos;
				kind = 0x7fffffff;
			}
			++curPos;
			if ((i = jjnewStateCnt) == (startsAt = 16 - (jjnewStateCnt = startsAt)))
				return curPos;
			try {
				curChar = input_stream.readChar();
			} catch (java.io.IOException e) {
				return curPos;
			}
		}
	}

	private int jjMoveStringLiteralDfa0_0() {
		switch (curChar) {
		case 13:
			jjmatchedKind = 3;
			return jjMoveStringLiteralDfa1_0(0x10L);
		case 40:
			return jjStopAtPos(0, 9);
		case 41:
			return jjStopAtPos(0, 10);
		case 42:
			return jjStopAtPos(0, 6);
		case 43:
			return jjStopAtPos(0, 5);
		case 45:
			return jjStopAtPos(0, 8);
		case 47:
			return jjStopAtPos(0, 14);
		case 60:
			return jjStartNfaWithStates_0(0, 11, 1);
		case 62:
			return jjStopAtPos(0, 12);
		case 63:
			return jjStopAtPos(0, 7);
		case 124:
			return jjStopAtPos(0, 13);
		default:
			return jjMoveNfa_0(0, 0);
		}
	}

	private int jjMoveStringLiteralDfa1_0(long active0) {
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(0, active0);
			return 1;
		}
		switch (curChar) {
		case 10:
			if ((active0 & 0x10L) != 0L)
				return jjStopAtPos(1, 4);
			break;
		default:
			break;
		}
		return jjStartNfa_0(0, active0);
	}

	private final int jjStartNfa_0(int pos, long active0) {
		return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
	}

	private int jjStartNfaWithStates_0(int pos, int kind, int state) {
		jjmatchedKind = kind;
		jjmatchedPos = pos;
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			return pos + 1;
		}
		return jjMoveNfa_0(state, pos + 1);
	}

	private int jjStopAtPos(int pos, int kind) {
		jjmatchedKind = kind;
		jjmatchedPos = pos;
		return pos + 1;
	}

	private final int jjStopStringLiteralDfa_0(int pos, long active0) {
		switch (pos) {
		case 0:
			if ((active0 & 0x800L) != 0L)
				return 1;
			return -1;
		default:
			return -1;
		}
	}

	/** Reinitialise parser. */
	public void ReInit(SimpleCharStream stream) {
		jjmatchedPos = jjnewStateCnt = 0;
		curLexState = defaultLexState;
		input_stream = stream;
		ReInitRounds();
	}

	/** Reinitialise parser. */
	public void ReInit(SimpleCharStream stream, int lexState) {
		ReInit(stream);
		SwitchTo(lexState);
	}

	private void ReInitRounds() {
		int i;
		jjround = 0x80000001;
		for (i = 16; i-- > 0;)
			jjrounds[i] = 0x80000000;
	}

	/** Set debug output. */
	public void setDebugStream(java.io.PrintStream ds) {
		debugStream = ds;
	}

	/** Switch to specified lex state. */
	public void SwitchTo(int lexState) {
		if (lexState >= 1 || lexState < 0)
			throw new TokenMgrError("Error: Ignoring invalid lexical state : "
					+ lexState + ". State unchanged.",
					TokenMgrError.INVALID_LEXICAL_STATE);
		else
			curLexState = lexState;
	}

}
